version: '3.7'
services:
  microservice-answer:
    container_name: "microservice-answer"
    image: microservice-answer
    env_file:
      - settings_server.env
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - 7000:7000
    command: ["/app/docker/app.sh"]
    depends_on:
      - db
    #networks:
    #  - default
  db:
    image: postgres:latest
    container_name: db_app
    restart: always
    expose:
      - 5400
    ports:
      - 5400:5400
    env_file:
      - settings_server.env
    #networks:
    #  - default

#networks:
#  default:
#    external: true
#    name: agu-review

