from .AnswerRepository import AnswerRepository
from .TaskRepository import TaskRepository
from .TypeCompilationRepository import TypeCompilationRepository
from .ContestReportRepository import ContestReportRepository
